---
title: "Overdispersion tests"
author: "Michal Burdukiewicz"
date: "9. September 2015"
output: 
  html_document:
    toc: true
bibliography: overdispersion.bib
---

Abbrevations:  
* BM - binomial model  
* DM - dispersed model  
* PM - Poisson model  
* NM - non-dispersed model  
* QBM - quasibinomial model  
* QPM - quasi-Poisson model   
* ZDP - zero-deflated Poisson (distribution)   
* ZIP - zero-inflated Poisson (distribution)    
* ZTP - zero-truncated Poisson (distribution)   

# Theoretical introduction  

## COM distribution (both ZIP and ZDP)

See in @shmueli_useful_2005.

COM can be both under- and overdispersed.

$$
P(X = k) = \frac{\lambda^k}{(k!)^\nu Z}
$$

If $\nu = 1$, it is normal Poisson distribution. Overdispersed when $0 < \nu < 1$ and underdispersed when $\nu > 1$.    
Disadvantage: $\nu$ is quite hard to interpret.

Implemented in the package [compoisson](https://cran.r-project.org/web/packages/compoisson/index.html).



## Zero-inflated distribution 
$$
P\{X = K\} = \begin{cases}
(1 - p) + p \exp^{-\lambda},\text{if } k = 0\\
p \frac{\lambda^k \exp^{-\lambda}}{k!},\text{if } k = 1, 2, \ldots
\end{cases}
$$
as in @wang_comparison_2012.

Mean:
$$
\mu = p \lambda
$$

Variance:
$$
\mu = p \lambda + p(1 - p)\lambda^2
$$

So when p=1, we have Poisson distribution.


# Publications

## Likelihood ratio test for over-dispersion in count data

Compute likelihood ratio for null hypothesis:

$$
H_0: \mu = \sigma^2 
$$

If rejected, negative binomial distribution is assumed. But negative binomial distribution is not equivalent to quasi-Poisson distribution (real distribution vs quasi-distribution). For more empirical comparison see @ver_hoef_quasi-poisson_2007

### Implementation
[odTest in package pscl](http://www.inside-r.org/packages/cran/pscl/docs/odTest)

## Regression-based tests for overdispersion in the Poisson model

@cameron_regression-based_1990

### Implementation
[dispersiontest  in package AER](http://artax.karlin.mff.cuni.cz/r-help/library/AER/html/dispersiontest.html)

## An extension of an over-dispersion test for count data

Test for 0-truncated data (unknown number of 0 counts) [@baksh_extension_2011].

### Implementation
Not found.

## A Test for Quasi-Binomial Distribution

@fazal_test_1976

### Implementation
Not found.

## Additonal stuff
http://www.inside-r.org/packages/cran/qcc/docs/qcc.overdispersion.test

## Bohning's test for overdispersion of Poisson data



### Implementation
http://rpackages.ianhowson.com/cran/epiR/man/epi.bohning.html

## References

